from constants import *
from classes import BLOATWARE

BLOATWARE_APPLICATION_LIST = [
    "Microsoft.3DBuilder",
    "Microsoft.Microsoft3DViewer",
    "Microsoft.MixedReality.Portal",
    "*Microsoft.549981C3F5F10", #CORTANA,
    "*Microsoft.549981C3F5F10*", #CORTANA,
    "Microsoft.WindowsCommunicationsApps",
    "Microsoft.Messaging",
    "Microsoft.People",
    "Microsoft.SkypeApp",
    "Microsoft.YourPhone",
    "Microsoft.XboxApp",
    "Microsoft.XboxGameOverlay",
    "Microsoft.XboxGamingOverlay",
    "Microsoft.ZuneMusic",
    "Microsoft.ZuneVideo",
    # "Microsoft.Windows.Photos",
    "Microsoft.WindowsAlarms",
    "Microsoft.WindowsMaps",
    "Microsoft.ScreenSketch",
    "Microsoft.MicrosoftSolitaireCollection", 
    "Microsoft.WindowsSoundRecorder",
    "Microsoft.MicrosoftStickyNotes",
    "Microsoft.BingWeather",
    "Microsoft.BingFinance",
    "Microsoft.BingSports",
    "*linkedin*",
    "Microsoft.MicrosoftOfficeHub",
    "Microsoft.Office.Word",
    "Microsoft.Office.Excel",
    "Microsoft.Office.Powerpoint",
    "Microsoft.Office.Outlook",
    "Microsoft.OneDrive",
    "Microsoft.OneConnect",
    "Microsoft.Office.OneNote",
    "Microsoft.WindowsFeedbackHub",
    "Microsoft.GetHelp",
    "Microsoft.Getstarted",
    "Microsoft.MSPaint",
    "Microsoft.Wallet",
]